// DEFAULT TYPE
export interface IAction {
  type: string;
}

export type InferValueTypes<T> = T extends { [key: string]: infer U }
  ? U
  : never;

// App
export const CHECK_ADMIN_KEY = "CHECK_ADMIN_KEY";
export const CHECK_ADMIN_KEY_SUCCESS = "CHECK_ADMIN_KEY_SUCCESS";
export const CHECK_ADMIN_KEY_FAILED = "CHECK_ADMIN_KEY_FAILED";

// MainScreen
export const CHANGE_SEARCH_GROUP_NAME = "CHANGE_SEARCH_GROUP_NAME";

// GroupScreen
export const CHANGE_SEARCH_LESSON_NAME = "CHANGE_SEARCH_LESSON_NAME";
export const ADD_LESSON = "ADD_LESSON";
export const ADD_LESSON_SUCCESS = "ADD_LESSON_SUCCESS";
export const ADD_LESSON_FAILED = "ADD_LESSON_FAILED";

// Groups
export const DOWNLOAD_GROUPS = "DOWNLOAD_GROUPS";
export const DOWNLOAD_GROUPS_SUCCESS = "DOWNLOAD_GROUPS_SUCCESS";
export const DOWNLOAD_GROUPS_FAILED = "DOWNLOAD_GROUPS_FAILES";

export const CREATE_GROUP = "CREATE_GROUP";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILED = "CREATE_GROUP_FAILED";

export const REMOVE_GROUP = "REMOVE_GROUP";
export const REMOVE_GROUP_SUCCESS = "REMOVE_GROUP_SUCCESS";
export const REMOVE_GROUP_FAILED = "REMOVE_GROUP_FAILED";

export const CHANGE_GROUP_TITLE = "CHANGE_GROUP_TITLE";
export const CHANGE_GROUP_TITLE_SUCCESS = "CHANGE_GROUP_TITLE_SUCCESS";
export const CHANGE_GROUP_TITLE_FAILED = "CHANGE_GROUP_TITLE_FAILED";

// Lessons
export const DOWNLOAD_LESSONS = "DOWNLOAD_LESSONS";
export const DOWNLOAD_LESSONS_SUCCESS = "DOWNLOAD_LESSONS_SUCCESS";
export const DOWNLOAD_LESSONS_FAILED = "DOWNLOAD_LESSONS_FAILES";

export const CREATE_LESSON = "CREATE_LESSON";
export const CREATE_LESSON_SUCCESS = "CREATE_LESSON_SUCCESS";
export const CREATE_LESSON_FAILED = "CREATE_LESSON_FAILED";

export const REMOVE_LESSON = "REMOVE_LESSON";
export const REMOVE_LESSON_SUCCESS = "REMOVE_LESSON_SUCCESS";
export const REMOVE_LESSON_FAILED = "REMOVE_LESSON_FAILED";

export const CHANGE_LESSON = "CHANGE_LESSON";
export const CHANGE_LESSON_SUCCESS = "CHANGE_LESSON_SUCCESS";
export const CHANGE_LESSON_FAILED = "CHANGE_LESSON_FAILED";
