// DEFAULT TYPE
export interface IAction {
  type: string;
}

export type InferValueTypes<T> = T extends { [key: string]: infer U }
  ? U
  : never;

// Groups
export const DOWNLOAD_GROUPS = "DOWNLOAD_GROUPS";
export const DOWNLOAD_GROUPS_SUCCESS = "DOWNLOAD_GROUPS_SUCCESS";
export const DOWNLOAD_GROUPS_FAILES = "DOWNLOAD_GROUPS_FAILES";

export const CREATE_GROUP = "CREATE_GROUP";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILED = "CREATE_GROUP_FAILED";

export const REMOVE_GROUP = "REMOVE_GROUP";
export const REMOVE_GROUP_SUCCESS = "REMOVE_GROUP_SUCCESS";
export const REMOVE_GROUP_FAILED = "REMOVE_GROUP_FAILED";

// Lessons
export const DOWNLOAD_LESSONS = "DOWNLOAD_LESSONS";
export const DOWNLOAD_LESSONS_SUCCESS = "DOWNLOAD_LESSONS_SUCCESS";
export const DOWNLOAD_LESSONS_FAILES = "DOWNLOAD_LESSONS_FAILES";

export const CREATE_LESSON = "CREATE_LESSON";
export const CREATE_LESSON_SUCCESS = "CREATE_LESSON_SUCCESS";
export const CREATE_LESSON_FAILED = "CREATE_LESSON_FAILED";

export const REMOVE_LESSON = "REMOVE_LESSON";
export const REMOVE_LESSON_SUCCESS = "REMOVE_LESSON_SUCCESS";
export const REMOVE_LESSON_FAILED = "REMOVE_LESSON_FAILED";
